import { ProjectInfo } from "./projectInfo";

export const projectData: ProjectInfo[] = [
    new ProjectInfo('Spence',
        'Spence is a Flutter-based mobile app for tracking the shelf life of pantry items, medicines, cosmetics, and more by storing expiry dates in Firebase.',
        'https://github.com/MS07062000/spence',
        'https://www.youtube.com/watch?v=uA8kV7FX8Gw',
        'https://img.youtube.com/vi/uA8kV7FX8Gw/mqdefault.jpg',
        ''),
    new ProjectInfo('Spence',
        'Spence is a Flutter-based mobile app for tracking the shelf life of pantry items, medicines, cosmetics, and more by storing expiry dates in Firebase.',
        'https://github.com/MS07062000/spence',
        'https://www.youtube.com/watch?v=uA8kV7FX8Gw',
        'https://img.youtube.com/vi/uA8kV7FX8Gw/mqdefault.jpg',
        ''),
    new ProjectInfo('FlightSearch',
        'The Flight Search Application is developed using HTML, CSS, JS, Node.js, and Express.js, enabling users to search for one-way, multi-way, and round-trip flights based on their criteria.',
        'https://github.com/MS07062000/toursandtravels',
        'https://www.youtube.com/watch?v=Uk5gadtpViQ',
        'https://img.youtube.com/vi/Uk5gadtpViQ/mqdefault.jpg',
        'https://toursandtravels-7sng.onrender.com/flights'),
    new ProjectInfo('YelpCamp',
        'Explore camping grounds, read reviews, and connect with outdoor enthusiasts on this user-friendly website. Share your experiences and discover the best spots for your next adventure',
        'https://github.com/MS07062000/campingWebsite',
        'https://www.youtube.com/watch?v=gGzljDgcpz0',
        'https://img.youtube.com/vi/gGzljDgcpz0/mqdefault.jpg',
        'https://yelpcamp-9gsq.onrender.com/landing'),

    new ProjectInfo('Location Notes',
        'Location-based to-do list app powered by Flutter & Google Maps API. Create tasks for specific spots, simplifying task management.',
        'https://github.com/MS07062000/To_Do_List_App',
        'https://www.youtube.com/watch?v=w9pjKrxJUCg',
        'https://img.youtube.com/vi/w9pjKrxJUCg/mqdefault.jpg',
        ''),
    new ProjectInfo('Youtube Clone',
        'This project is built on Material UI and React. It utilizes the Rapid API for certain functionalities.',
        'https://github.com/MS07062000/YoutubeClone',
        '',
        'https://i.pinimg.com/originals/14/e5/84/14e584760464db3248dd7c57e15d577a.jpg',
        'https://youtube-clone-ms07062000.vercel.app/'
    ),
    new ProjectInfo('EZ Car Registration Services',
    'This project is built on Vite and React.',
    'https://github.com/Honshu11/ez-car-landing-page',
    '',
    'https://ez-car-landing-page-alpha.vercel.app/Images/ezlogo2.png',
    'https://ez-car-landing-page-alpha.vercel.app/'
),

];